server:
  address: 0.0.0.0
  port: ${DISCOVERY_PORT}

spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:${CONFIG_PORT}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-repository: false
    service-uri:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


